# Generated by Django 4.1.1 on 2022-10-07 23:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="canciones",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=30)),
                ("autor", models.CharField(max_length=30)),
                ("album", models.CharField(max_length=30)),
                ("dircan", models.FileField(upload_to="Canciones/")),
                ("genero", models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name="playli",
            fields=[
                (
                    "User",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("NomPlay", models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name="Tipos",
            fields=[
                (
                    "User",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("TipoUser", models.CharField(max_length=10)),
                ("TiempoSus", models.IntegerField()),
            ],
        ),
    ]
