# Generated by Django 4.1.1 on 2022-10-07 23:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("NekoMusic", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="canciones",
            name="playlis",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="NekoMusic.playli",
            ),
            preserve_default=False,
        ),
    ]
