# Generated by Django 4.1.1 on 2022-10-08 00:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("NekoMusic", "0002_canciones_playlis"),
    ]

    operations = [
        migrations.AlterField(
            model_name="canciones",
            name="playlis",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="playli",
                to="NekoMusic.playli",
            ),
        ),
    ]
