# Generated by Django 4.1.1 on 2022-10-08 04:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("NekoMusic", "0003_alter_canciones_playlis"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="canciones",
            name="playlis",
        ),
        migrations.RemoveField(
            model_name="playli",
            name="User",
        ),
        migrations.AddField(
            model_name="playli",
            name="ID_Can",
            field=models.ManyToManyField(null=True, to="NekoMusic.canciones"),
        ),
        migrations.AddField(
            model_name="playli",
            name="ID_Usu",
            field=models.ManyToManyField(null=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="playli",
            name="id",
            field=models.BigAutoField(
                auto_created=True,
                default=None,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
            preserve_default=False,
        ),
    ]
