# Generated by Django 4.1.1 on 2022-10-09 20:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("NekoMusic", "0004_remove_canciones_playlis_remove_playli_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="playli",
            name="ID_Can",
            field=models.ManyToManyField(to="NekoMusic.canciones"),
        ),
        migrations.AlterField(
            model_name="playli",
            name="ID_Usu",
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
