# Generated by Django 4.1.1 on 2022-10-17 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("NekoMusic", "0005_alter_playli_id_can_alter_playli_id_usu"),
    ]

    operations = [
        migrations.AlterField(
            model_name="canciones",
            name="album",
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name="canciones",
            name="autor",
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name="canciones",
            name="nombre",
            field=models.CharField(max_length=40),
        ),
    ]
