# Generated by Django 4.1.1 on 2022-11-13 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("NekoMusic", "0006_alter_canciones_album_alter_canciones_autor_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="playli",
            name="ID_Can",
            field=models.ManyToManyField(null=True, to="NekoMusic.canciones"),
        ),
    ]
