# Generated by Django 4.1.1 on 2022-11-13 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("NekoMusic", "0010_remove_playli_id_can"),
    ]

    operations = [
        migrations.AddField(
            model_name="playli",
            name="ID_Can",
            field=models.ManyToManyField(null=True, to="NekoMusic.canciones"),
        ),
    ]
