# Generated by Django 4.1.1 on 2022-11-13 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("NekoMusic", "0011_playli_id_can"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="playli",
            name="ID_Can",
        ),
        migrations.RemoveField(
            model_name="playli",
            name="ID_Usu",
        ),
    ]
