# Generated by Django 4.1.1 on 2022-11-13 20:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("NekoMusic", "0012_remove_playli_id_can_remove_playli_id_usu"),
    ]

    operations = [
        migrations.AddField(
            model_name="playli",
            name="ID_Can",
            field=models.ManyToManyField(null=True, to="NekoMusic.canciones"),
        ),
        migrations.AddField(
            model_name="playli",
            name="ID_Usu",
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
